dist: xenial
addons:
  snaps:
    - go

# language: node_js

# node_js:
  # - "node"
  # - "lts/*"

cache:
  directories:
    - "node_modules"
    - "seedutil/go" # go modules used for xudseed
    # - "test/simulation/go" # lnd, btcd, and dependencies

      # before_install:
      # - eval "$(GIMME_GO_VERSION=1.12.9 gimme)"

script:
  # - npm run lintNoFix
  # - npm run compile:seedutil
  # - npm run test
  # - npm run test:sim
  # - cd test/simulation && ./geth.sh
  - git clone https://github.com/ethereum/go-ethereum "$GOPATH/src/github.com/ethereum/go-ethereum"
  - cd "$GOPATH/src/github.com/ethereum/go-ethereum"
  - git checkout v1.9.2
  - echo $(git --version)
  - go run build/ci.go install ./cmd/geth
