language: node_js

node_js:
  - "node"
  - "lts/*"

cache:
  directories:
    - "node_modules"
    - "seedutil/go" # go modules used for xudseed
    - "test/simulation/go" # lnd, btcd, and dependencies

before_install:
  - npm install grpc@1.24.1 --build-from-source
  - eval "$(GIMME_GO_VERSION=1.12 gimme)"

script:
  - npm run lintNoFix
  - npm run test
  - npm run test:sim
  - npm run compile:seedutil
  - npm run test:seedutil
